package com.example.shopper2021

import android.content.Intent
import android.os.Bundle
import android.view.Menu
import android.view.MenuItem
import android.view.View
import android.widget.AdapterView.OnItemClickListener
import android.widget.ListView
import androidx.appcompat.app.AppCompatActivity
import androidx.appcompat.widget.Toolbar
import com.example.shopper2021.MainActivity

class MainActivity : AppCompatActivity() {
    // declare an Intent
    // var intent: Intent? = null

    // declare a DBHandler
    var dbHandler: DBHandler? = null

    // declare a ShoppingLists Cursor Adapter
    var shoppingListsAdapter: ShoppingLists? = null

    // declare a ListView
    var shopperListView: ListView? = null

    /**
     * This method initializes the Action Bar and View of the MainActivity.
     * @param savedInstanceState a Bundle object that is passed into the
     * onCreate method of every Android Activity.
     * Activities have the ability, under special
     * circumstances, to restore themselves to a
     * previous state using the data stored in this
     * object.  If there is no available instance
     * data, the object will be null.
     */
    override fun onCreate(savedInstanceState: Bundle?) {

        // code generated by Android Studio that initializes the View and
        // Action Bar of the MainActivity
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val toolbar = findViewById<Toolbar>(R.id.toolbar)
        setSupportActionBar(toolbar)

        // initialize DBHandler
        dbHandler = DBHandler(this, null)

        // initialize ListView
        shopperListView = findViewById<View>(R.id.shopperListView) as ListView

        // initialize the ShoppingLists Cursor Adapter
        shoppingListsAdapter = ShoppingLists(this, dbHandler!!.shoppingLists, 0)

        // set ShoppingLists Cursor Adapter on ListView
        shopperListView!!.adapter = shoppingListsAdapter

        // register an On Item Click Listener on ListView
        shopperListView!!.onItemClickListener = OnItemClickListener { parent, view, position, id ->
            /**
             * This method gets called when a row in the ListView is clicked.
             * @param parent shopperListView
             * @param view MainActivity view
             * @param position position of clicked row
             * @param id database id of clicked row
             */
            /**
             * This method gets called when a row in the ListView is clicked.
             * @param parent shopperListView
             * @param view MainActivity view
             * @param position position of clicked row
             * @param id database id of clicked row
             */

            // initialize Intent for ViewList Activity
            intent = Intent(this@MainActivity, ViewList::class.java)

            // put the database id in the Intent
            intent!!.putExtra("_id", id)

            // start the ViewList Activity
            startActivity(intent)
        }
    }

    /**
     * This method further initializes the Action Bar of the MainActivity.
     * It gets the code in the menu main resource file and incorporates it
     * into the Action Bar.
     * @param menu menu main resource file
     * @return true
     */
    override fun onCreateOptionsMenu(menu: Menu): Boolean {
        // Inflate the menu main; this adds items to the action bar if it is present.
        menuInflater.inflate(R.menu.menu_main, menu)
        return true
    }

    /**
     * This method gets called when a menu item in the overflow menu is
     * selected and it controls what happens when the menu item is selected.
     * @param item selected menu item in overflow menu
     * @return true if menu item is selected, else false
     */
    override fun onOptionsItemSelected(item: MenuItem): Boolean {
        // get the id of the menu item selected
        return when (item.itemId) {
            R.id.action_home -> {
                // initialize an Intent for the MainActivity and start it
                // if the id is for the MainActivity
                intent = Intent(this, MainActivity::class.java)
                startActivity(intent)
                true
            }
            R.id.action_create_list -> {
                // initialize an Intent for the CreateList Activity and start it
                // if the id is for the CreateList Activity
                intent = Intent(this, CreateList::class.java)
                startActivity(intent)
                true
            }
            else -> super.onOptionsItemSelected(item)
        }
    }

    /**
     * This method gets called when the add Floating Action Button is clicked.
     * It starts the CreateList Activity.
     * @param view MainActivity view
     */
    fun openCreateList(view: View?) {
        intent = Intent(this, CreateList::class.java)
        startActivity(intent)
    }
}