package com.example.shopper2021;

import android.content.Intent;
import android.os.Bundle;

import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.google.android.material.snackbar.Snackbar;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;

import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ListView;
import android.widget.Toast;

public class ViewList extends AppCompatActivity {

    // declare an Intent
    Intent intent;

    // declare a Bundle and a long for data passed from MainActivity in Bundle
    Bundle bundle;
    long id;

    // declare a DBHandler
    DBHandler dbHandler;

    // declare a ShoppingListItems Cursor Adapter
    ShoppingListItems shoppingListItemsAdapter;

    // declare a ListView
    ListView itemListView;

    /**
     * This method initializes the Action Bar and View of the ViewList Activity.
     * @param savedInstanceState a Bundle object that is passed into the
     *                           onCreate method of every Android Activity.
     *                           Activities have the ability, under special
     *                           circumstances, to restore themselves to a
     *                           previous state using the data stored in this
     *                           object.  If there is no available instance
     *                           data, the object will be null.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {

        // code generated by Android Studio that initializes the View and
        // Action Bar of the ViewList Activity
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_view_list);
        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        // initialize Bundle
        bundle = this.getIntent().getExtras();

        // get shopping list id passed in Bundle and store it in long
        id = bundle.getLong("_id");

        // initialize DBHandler
        dbHandler = new DBHandler(this, null);

        // get shopping list name
        String shoppingListName = dbHandler.getShoppingListName((int) id);

        // set the Title of the ViewList activity to the shopping list name
        this.setTitle(shoppingListName);

        // initialize ListView
        itemListView = (ListView) findViewById(R.id.itemsListView);

        // initialize ShoppingListItems CursorAdapter
        shoppingListItemsAdapter = new ShoppingListItems(this, dbHandler.getShoppingListItems((int) id), 0);

        // set ShoppingListItems CursorAdapter on ListView
        itemListView.setAdapter(shoppingListItemsAdapter);

        // register an On Item Click Listener on ListView
        itemListView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            /**
             * This method gets called when a row in the ListView is clicked.
             * @param parent itemListView
             * @param view ViewList Activity view
             * @param position position of clicked row
             * @param id database id of clicked row
             */
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                // call method that updates a shopping list item's item_has attribute
                // to true if it hasn't already been set to true
                updateItem(id);

                // initialize Intent for ViewItem Activity
                intent = new Intent(ViewList.this, ViewItem.class);

                // put the database id in the Intent
                intent.putExtra("_id", id);

                // start the Activity
                startActivity(intent);
            }
        });
    }

    /**
     * This method further initializes the Action Bar of the ViewList Activity.
     * It gets the code in the menu main resource file and incorporates it
     * into the Action Bar.
     * @param menu menu view list resource file
     * @return true
     */
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu view list; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_view_list, menu);
        return true;
    }

    /**
     * This method gets called when a menu item in the overflow menu is
     * selected and it controls what happens when the menu item is selected.
     * @param item selected menu item in overflow menu
     * @return true if menu item is selected, else false
     */
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // get the id of the menu item selected
        switch (item.getItemId()) {
            case R.id.action_home :
                // initialize an Intent for the MainActivity and start it
                // if the id is for the MainActivity
                intent = new Intent(this, MainActivity.class);
                startActivity(intent);
                return true;
            case R.id.action_create_list :
                // initialize an Intent for the CreateList Activity and start it
                // if the id is for the CreateList Activity
                intent = new Intent(this, CreateList.class);
                startActivity(intent);
                return true;
            case R.id.action_add_item:
                // initialize an Intent for the AddItem Activity
                intent = new Intent(this, AddItem.class);
                // put the database id in the Intent
                intent.putExtra("_id", id);
                // start the Activity
                startActivity(intent);
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }

    /**
     * This method gets called when the add Floating Action Button is clicked.
     * It starts the AddItem Activity.
     * @param view ViewList view
     */
    public void openAddItem(View view) {

        // initialize an Intent for the AddItem Activity
        intent = new Intent(this, AddItem.class);
        // put the database id in the Intent
        intent.putExtra("_id", id);
        // start the Activity
        startActivity(intent);
    }

    /**
     * This method updates a shopping list item's item_has attribute to true if
     * it hasn't already been set to true.
     * @param id shopping list item's id
     */
    public void updateItem(long id) {

        // if shopping list item hasn't been purchased
        if (dbHandler.isItemUnPurchased((int) id) != 0){
            // update its item_has to true
            dbHandler.updateItem((int) id);

            // display Toast indicating shopping list item has been purchased
            Toast.makeText(this, "Item purchased!", Toast.LENGTH_LONG).show();

            // refresh shopping list item in the ListView
            shoppingListItemsAdapter.swapCursor(dbHandler.getShoppingListItems((int) id));
            shoppingListItemsAdapter.notifyDataSetChanged();
        }
    }
}