package com.example.shopper2021;

import android.content.Intent;
import android.os.Bundle;

import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.google.android.material.snackbar.Snackbar;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;

import android.view.Menu;
import android.view.MenuItem;
import android.view.View;

public class ViewList extends AppCompatActivity {

    // declare an Intent
    Intent intent;

    // declare a Bundle and a long for data passed from MainActivity in Bundle
    Bundle bundle;
    long id;

    // declare a DBHandler
    DBHandler dbHandler;

    /**
     * This method initializes the Action Bar and View of the ViewList Activity.
     * @param savedInstanceState a Bundle object that is passed into the
     *                           onCreate method of every Android Activity.
     *                           Activities have the ability, under special
     *                           circumstances, to restore themselves to a
     *                           previous state using the data stored in this
     *                           object.  If there is no available instance
     *                           data, the object will be null.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {

        // code generated by Android Studio that initializes the View and
        // Action Bar of the ViewList Activity
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_view_list);
        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        // initialize Bundle
        bundle = this.getIntent().getExtras();

        // get shopping list id passed in Bundle and store it in long
        id = bundle.getLong("_id");

        // initialize DBHandler
        dbHandler = new DBHandler(this, null);

        // get shopping list name
        String shoppingListName = dbHandler.getShoppingListName((int) id);

        // set the Title of the ViewList activity to the shopping list name
        this.setTitle(shoppingListName);
    }

    /**
     * This method further initializes the Action Bar of the ViewList Activity.
     * It gets the code in the menu main resource file and incorporates it
     * into the Action Bar.
     * @param menu menu view list resource file
     * @return true
     */
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu view list; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_view_list, menu);
        return true;
    }

    /**
     * This method gets called when a menu item in the overflow menu is
     * selected and it controls what happens when the menu item is selected.
     * @param item selected menu item in overflow menu
     * @return true if menu item is selected, else false
     */
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // get the id of the menu item selected
        switch (item.getItemId()) {
            case R.id.action_home :
                // initialize an Intent for the MainActivity and start it
                // if the id is for the MainActivity
                intent = new Intent(this, MainActivity.class);
                startActivity(intent);
                return true;
            case R.id.action_create_list :
                // initialize an Intent for the CreateList Activity and start it
                // if the id is for the CreateList Activity
                intent = new Intent(this, CreateList.class);
                startActivity(intent);
                return true;
            case R.id.action_add_item:
                // initialize an Intent for the AddItem Activity and start it
                // if the id is for the CreateList Activity
                intent = new Intent(this, AddItem.class);
                // put the database id in the Intent
                intent.putExtra("_id", id);
                startActivity(intent);
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }

    /**
     * This method gets called when the add Floating Action Button is clicked.
     * It starts the AddItem Activity.
     * @param view ViewList view
     */
    public void openAddItem(View view) {

        // initialize an Intent for the AddItem Activity and start it
        // if the id is for the CreateList Activity
        intent = new Intent(this, AddItem.class);
        // put the database id in the Intent
        intent.putExtra("_id", id);
        startActivity(intent);
    }
}